Repository AconInc/ACON-SERVER, pull requests merged in 2025-02, with the labels that each got.

#74 [FEAT/#73] 토큰 재발급 / 로그아웃 / 회원 탈퇴 기능 구현
  build.gradle
  src/main/java/com/acon/server/global/auth/CacheConfig.java
  src/main/java/com/acon/server/global/auth/jwt/JwtTokenProvider.java
  src/main/java/com/acon/server/global/exception/ErrorType.java
  src/main/java/com/acon/server/member/api/controller/MemberController.java
  src/main/java/com/acon/server/member/api/request/LogoutRequest.java
  src/main/java/com/acon/server/member/api/request/ReissueTokenRequest.java
  src/main/java/com/acon/server/member/api/request/WithdrawalReasonRequest.java
  src/main/java/com/acon/server/member/api/response/ReissueTokenResponse.java
  src/main/java/com/acon/server/member/application/service/MemberService.java
  src/main/java/com/acon/server/member/infra/entity/WithdrawalReasonEntity.java
  src/main/java/com/acon/server/member/infra/repository/WithdrawalReasonRepository.java
Labels: ✨ FEAT, 🦊 가현, size/M

#72 [FEAT/#71] 내 프로필 조회 API 구현
  build.gradle
  src/main/java/com/acon/server/global/auth/CacheConfig.java
  src/main/java/com/acon/server/global/auth/jwt/JwtTokenProvider.java
  src/main/java/com/acon/server/global/exception/ErrorType.java
  src/main/java/com/acon/server/member/api/controller/MemberController.java
  src/main/java/com/acon/server/member/api/request/LogoutRequest.java
  src/main/java/com/acon/server/member/api/request/ReissueTokenRequest.java
  src/main/java/com/acon/server/member/api/request/WithdrawalReasonRequest.java
  src/main/java/com/acon/server/member/api/response/ProfileResponse.java
  src/main/java/com/acon/server/member/api/response/ReissueTokenResponse.java
  src/main/java/com/acon/server/member/application/service/MemberService.java
  src/main/java/com/acon/server/member/infra/entity/MemberEntity.java
  src/main/java/com/acon/server/member/infra/entity/WithdrawalReasonEntity.java
  src/main/java/com/acon/server/member/infra/repository/VerifiedAreaRepository.java
  src/main/java/com/acon/server/member/infra/repository/WithdrawalReasonRepository.java
Labels: ✨ FEAT, 🦊 가현, size/L

#81 [FEAT/#76] PreSigned URL 획득 API 구현
  build.gradle
  src/main/java/com/acon/server/global/exception/ErrorType.java
  src/main/java/com/acon/server/global/external/maps/GeoCodingResponse.java
  src/main/java/com/acon/server/global/external/maps/NaverMapsAdapter.java
  src/main/java/com/acon/server/global/external/maps/NaverMapsClient.java
  src/main/java/com/acon/server/global/external/maps/NaverMapsFeignConfig.java
  src/main/java/com/acon/server/global/external/s3/S3Adapter.java
  src/main/java/com/acon/server/global/external/s3/S3Config.java
  src/main/java/com/acon/server/member/api/controller/MemberController.java
  src/main/java/com/acon/server/member/api/response/PreSignedUrlResponse.java
  src/main/java/com/acon/server/member/application/service/MemberService.java
  src/main/java/com/acon/server/member/domain/enums/ImageType.java
  src/main/java/com/acon/server/spot/application/service/SpotService.java
  src/main/java/com/acon/server/spot/domain/enums/FilterCategory.java
Labels: ✨ FEAT, 🐈‍⬛ 창균, size/M

#83 [FIX/#82] 중복 동네 인증 에러 수정
  src/main/java/com/acon/server/global/exception/ErrorType.java
  src/main/java/com/acon/server/member/api/controller/MemberController.java
  src/main/java/com/acon/server/member/api/response/AreaResponse.java
  src/main/java/com/acon/server/member/api/response/LoginResponse.java
  src/main/java/com/acon/server/member/api/response/MemberAreaResponse.java
  src/main/java/com/acon/server/member/application/service/MemberService.java
  src/main/java/com/acon/server/member/infra/repository/VerifiedAreaRepository.java
Labels: 🛠️ FIX, size/S

#86 [REFACTOR/#79] 온보딩 API PUT으로 변경
  src/main/java/com/acon/server/member/api/controller/MemberController.java
  src/main/java/com/acon/server/member/application/service/MemberService.java
Labels: ♻️ REFACTOR, 🐈‍⬛ 창균, size/XS

#85 [FEAT/#78] 프로필 수정 API 구현
  src/main/java/com/acon/server/global/exception/ErrorType.java
  src/main/java/com/acon/server/global/external/s3/S3Adapter.java
  src/main/java/com/acon/server/global/external/s3/S3Config.java
  src/main/java/com/acon/server/member/api/controller/MemberController.java
  src/main/java/com/acon/server/member/api/request/ProfileRequest.java
  src/main/java/com/acon/server/member/application/service/MemberService.java
  src/main/java/com/acon/server/member/domain/entity/Member.java
Labels: ✨ FEAT, 🐈‍⬛ 창균, size/M

#84 [FEAT/#77] 닉네임 유효성 검증 API 구현
  src/main/java/com/acon/server/global/exception/ErrorType.java
  src/main/java/com/acon/server/global/external/s3/S3Adapter.java
  src/main/java/com/acon/server/global/external/s3/S3Config.java
  src/main/java/com/acon/server/member/api/controller/MemberController.java
  src/main/java/com/acon/server/member/api/request/ProfileRequest.java
  src/main/java/com/acon/server/member/application/service/MemberService.java
  src/main/java/com/acon/server/member/domain/entity/Member.java
  src/main/java/com/acon/server/member/infra/repository/MemberRepository.java
Labels: ✨ FEAT, 🐈‍⬛ 창균, size/M

#88 [FEAT/#87] 인증 동네 리스트 조회 구현
  src/main/java/com/acon/server/global/exception/ErrorType.java
  src/main/java/com/acon/server/member/api/controller/MemberController.java
  src/main/java/com/acon/server/member/api/request/VerifiedAreaRequest.java
  src/main/java/com/acon/server/member/api/response/VerifiedAreaListResponse.java
  src/main/java/com/acon/server/member/api/response/VerifiedAreaResponse.java
  src/main/java/com/acon/server/member/application/service/MemberService.java
Labels: ✨ FEAT, 🦊 가현, size/S

#89 [REFACTOR/#75] API 엔드포인트 RESTful 규칙을 준수하도록 재정비
  src/main/java/com/acon/server/member/api/controller/MemberController.java
  src/main/java/com/acon/server/review/api/controller/ReviewController.java
  src/main/java/com/acon/server/spot/api/controller/SpotController.java
Labels: ♻️ REFACTOR, 🐈‍⬛ 창균, size/XS

#91 [FEAT/#90] 인증 동네 삭제 API 구현
  src/main/java/com/acon/server/global/exception/ErrorType.java
  src/main/java/com/acon/server/member/api/controller/MemberController.java
  src/main/java/com/acon/server/member/application/service/MemberService.java
  src/main/java/com/acon/server/member/infra/repository/MemberRepository.java
  src/main/java/com/acon/server/member/infra/repository/VerifiedAreaRepository.java
Labels: ✨ FEAT, 🐈‍⬛ 창균, size/S

#93 [FEAT/#92] 테스트 계정 위치 정보 강제 할당 및 서비스 미제공 지역에서 액세스 시 예외 처리 추가
  src/main/java/com/acon/server/global/exception/ErrorType.java
  src/main/java/com/acon/server/member/api/controller/MemberController.java
  src/main/java/com/acon/server/member/api/request/VerifiedAreaRequest.java
  src/main/java/com/acon/server/member/api/response/AreaResponse.java
  src/main/java/com/acon/server/member/application/service/MemberService.java
  src/main/java/com/acon/server/review/api/request/ReviewRequest.java
  src/main/java/com/acon/server/spot/api/controller/SpotController.java
  src/main/java/com/acon/server/spot/api/request/SpotListRequest.java
  src/main/java/com/acon/server/spot/application/service/SpotService.java
  src/main/java/com/acon/server/spot/infra/repository/SpotRepository.java
Labels: ✨ FEAT, 🐈‍⬛ 창균, size/M

#95 [FEAT/#94] 외부 분석 도구용 유저 고유 식별자 추가
  src/main/java/com/acon/server/member/api/response/LoginResponse.java
  src/main/java/com/acon/server/member/application/service/MemberService.java
  src/main/java/com/acon/server/member/domain/entity/Member.java
  src/main/java/com/acon/server/member/domain/vo/.gitkeep
  src/main/java/com/acon/server/member/domain/vo/MemberIdentifiersVO.java
  src/main/java/com/acon/server/member/infra/entity/MemberEntity.java
Labels: ✨ FEAT, 🐈‍⬛ 창균, size/S
