Repository AconInc/ACON-SERVER, pull requests merged in 2025-01, with the labels that each got.

#2 [SETTING/#1] PR 사이즈 라벨링 자동화
  .github/workflows/size-label.yml
Labels: 🦊 가현, ⚙️ SETTING

#10 [FEAT/#7] Member 도메인 내 도메인, 영속성 엔티티 작성
  build.gradle
  eclipse-formatter.xml
  src/main/java/com/acon/server/global/dto/ErrorResponse.java
  src/main/java/com/acon/server/global/exception/ErrorType.java
  src/main/java/com/acon/server/global/handler/GlobalExceptionHandler.java
  src/main/java/com/acon/server/member/application/mapper/.gitkeep
  src/main/java/com/acon/server/member/application/mapper/MemberMapper.java
  src/main/java/com/acon/server/member/application/mapper/PreferenceMapper.java
  src/main/java/com/acon/server/member/application/mapper/RecentGuidedSpotMapper.java
  src/main/java/com/acon/server/member/application/mapper/RecentViewedSpotMapper.java
  src/main/java/com/acon/server/member/application/mapper/VerifiedAreaMapper.java
  src/main/java/com/acon/server/member/domain/entity/.gitkeep
  src/main/java/com/acon/server/member/domain/entity/Member.java
  src/main/java/com/acon/server/member/domain/entity/Preference.java
  src/main/java/com/acon/server/member/domain/entity/RecentGuidedSpot.java
  src/main/java/com/acon/server/member/domain/entity/RecentViewedSpot.java
  src/main/java/com/acon/server/member/domain/entity/VerifiedArea.java
  src/main/java/com/acon/server/member/domain/enums/.gitkeep
  src/main/java/com/acon/server/member/domain/enums/Cuisine.java
  src/main/java/com/acon/server/member/domain/enums/DislikeFood.java
  src/main/java/com/acon/server/member/domain/enums/FavoriteSpot.java
  src/main/java/com/acon/server/member/domain/enums/SocialType.java
  src/main/java/com/acon/server/member/domain/enums/SpotStyle.java
  src/main/java/com/acon/server/member/domain/enums/SpotType.java
  src/main/java/com/acon/server/member/infra/entity/.gitkeep
  src/main/java/com/acon/server/member/infra/entity/MemberEntity.java
  src/main/java/com/acon/server/member/infra/entity/PreferenceEntity.java
  src/main/java/com/acon/server/member/infra/entity/RecentGuidedSpotEntity.java
  src/main/java/com/acon/server/member/infra/entity/RecentViewedSpotEntity.java
  src/main/java/com/acon/server/member/infra/entity/VerifiedAreaEntity.java
Labels: ✨ FEAT, 🐈‍⬛ 창균, size/XL

#6 [SETTING/#5] 프로젝트 초기 세팅
  .editorconfig
  build.gradle
  eclipse-formatter.xml
  src/main/java/com/acon/server/global/config/JpaAuditingConfig.java
  src/main/java/com/acon/server/global/dto/ErrorResponse.java
  src/main/java/com/acon/server/global/entity/BaseTimeEntity.java
  src/main/java/com/acon/server/global/exception/BusinessException.java
  src/main/java/com/acon/server/global/exception/ErrorType.java
  src/main/java/com/acon/server/global/handler/GlobalExceptionHandler.java
  src/main/java/com/acon/server/member/api/controller/.gitkeep
  src/main/java/com/acon/server/member/api/request/.gitkeep
  src/main/java/com/acon/server/member/api/response/.gitkeep
  src/main/java/com/acon/server/member/application/mapper/MemberMapper.java
  src/main/java/com/acon/server/member/application/mapper/PreferenceMapper.java
  src/main/java/com/acon/server/member/application/mapper/RecentGuidedSpotMapper.java
  src/main/java/com/acon/server/member/application/mapper/RecentViewedSpotMapper.java
  src/main/java/com/acon/server/member/application/mapper/VerifiedAreaMapper.java
  src/main/java/com/acon/server/member/application/service/.gitkeep
  src/main/java/com/acon/server/member/domain/entity/Member.java
  src/main/java/com/acon/server/member/domain/entity/Preference.java
  src/main/java/com/acon/server/member/domain/entity/RecentGuidedSpot.java
  src/main/java/com/acon/server/member/domain/entity/RecentViewedSpot.java
  src/main/java/com/acon/server/member/domain/entity/VerifiedArea.java
  src/main/java/com/acon/server/member/domain/enums/Cuisine.java
  src/main/java/com/acon/server/member/domain/enums/DislikeFood.java
  src/main/java/com/acon/server/member/domain/enums/FavoriteSpot.java
  src/main/java/com/acon/server/member/domain/enums/SocialType.java
  src/main/java/com/acon/server/member/domain/enums/SpotStyle.java
  src/main/java/com/acon/server/member/domain/enums/SpotType.java
  src/main/java/com/acon/server/member/domain/vo/.gitkeep
  src/main/java/com/acon/server/member/infra/entity/MemberEntity.java
  src/main/java/com/acon/server/member/infra/entity/PreferenceEntity.java
  src/main/java/com/acon/server/member/infra/entity/RecentGuidedSpotEntity.java
  src/main/java/com/acon/server/member/infra/entity/RecentViewedSpotEntity.java
  src/main/java/com/acon/server/member/infra/entity/VerifiedAreaEntity.java
  src/main/java/com/acon/server/member/infra/external/.gitkeep
  src/main/java/com/acon/server/member/infra/repository/.gitkeep
  src/main/java/com/acon/server/review/api/controller/.gitkeep
  src/main/java/com/acon/server/review/api/request/.gitkeep
  src/main/java/com/acon/server/review/api/response/.gitkeep
  src/main/java/com/acon/server/review/application/mapper/.gitkeep
  src/main/java/com/acon/server/review/application/service/.gitkeep
  src/main/java/com/acon/server/review/domain/entity/.gitkeep
  src/main/java/com/acon/server/review/domain/enums/.gitkeep
  src/main/java/com/acon/server/review/domain/vo/.gitkeep
  src/main/java/com/acon/server/review/infra/entity/.gitkeep
  src/main/java/com/acon/server/review/infra/external/.gitkeep
  src/main/java/com/acon/server/review/infra/repository/.gitkeep
  src/main/java/com/acon/server/spot/api/controller/.gitkeep
  src/main/java/com/acon/server/spot/api/request/.gitkeep
  src/main/java/com/acon/server/spot/api/response/.gitkeep
  src/main/java/com/acon/server/spot/application/mapper/.gitkeep
  src/main/java/com/acon/server/spot/application/service/.gitkeep
  src/main/java/com/acon/server/spot/domain/entity/.gitkeep
  src/main/java/com/acon/server/spot/domain/enums/.gitkeep
  src/main/java/com/acon/server/spot/domain/vo/.gitkeep
  src/main/java/com/acon/server/spot/infra/entity/.gitkeep
  src/main/java/com/acon/server/spot/infra/external/.gitkeep
  src/main/java/com/acon/server/spot/infra/repository/.gitkeep
Labels: 🐈‍⬛ 창균, ⚙️ SETTING, size/XL

#21 [FEAT/#20] 장소 메뉴 조회 API 구현
  src/main/java/com/acon/server/global/exception/ErrorType.java
  src/main/java/com/acon/server/spot/api/controller/.gitkeep
  src/main/java/com/acon/server/spot/api/controller/SpotController.java
  src/main/java/com/acon/server/spot/api/response/MenuListResponse.java
  src/main/java/com/acon/server/spot/api/response/MenuResponse.java
  src/main/java/com/acon/server/spot/application/service/SpotService.java
  src/main/java/com/acon/server/spot/domain/entity/Menu.java
  src/main/java/com/acon/server/spot/infra/entity/MenuEntity.java
  src/main/java/com/acon/server/spot/infra/repository/MenuRepository.java
  src/main/java/com/acon/server/spot/infra/repository/SpotRepository.java
Labels: ✨ FEAT, 🦊 가현, size/M

#23 [FEAT/#22] 최근 길 안내 장소 API 구현
  .editorconfig
  build.gradle
  eclipse-formatter.xml
  scripts/pre-commit
  src/main/java/com/acon/server/global/exception/ErrorType.java
  src/main/java/com/acon/server/member/api/controller/.gitkeep
  src/main/java/com/acon/server/member/api/controller/MemberController.java
  src/main/java/com/acon/server/member/api/request/.gitkeep
  src/main/java/com/acon/server/member/api/request/GuidedSpotRequest.java
  src/main/java/com/acon/server/member/application/service/.gitkeep
  src/main/java/com/acon/server/member/application/service/MemberService.java
  src/main/java/com/acon/server/member/infra/repository/.gitkeep
  src/main/java/com/acon/server/member/infra/repository/RecentGuidedSpotRepository.java
  src/main/java/com/acon/server/spot/infra/repository/.gitkeep
Labels: ✨ FEAT, 🦊 가현, size/XXL

#36 [FEAT/#24] 장소 상세정보 조회 API 구현
  build.gradle
  src/main/java/com/acon/server/global/config/AppStartupConfig.java
  src/main/java/com/acon/server/global/config/OpenFeignConfig.java
  src/main/java/com/acon/server/global/config/SchedulingConfig.java
  src/main/java/com/acon/server/global/config/properties/NaverMapsProperties.java
  src/main/java/com/acon/server/global/exception/ErrorType.java
  src/main/java/com/acon/server/global/external/GeoCodingResponse.java
  src/main/java/com/acon/server/global/external/NaverMapsAdapter.java
  src/main/java/com/acon/server/global/external/NaverMapsClient.java
  src/main/java/com/acon/server/global/external/NaverMapsFeignConfig.java
  src/main/java/com/acon/server/global/handler/GlobalExceptionHandler.java
  src/main/java/com/acon/server/global/scheduler/SpotScheduler.java
  src/main/java/com/acon/server/member/application/mapper/GuidedSpotMapper.java
  src/main/java/com/acon/server/member/application/mapper/RecentGuidedSpotMapper.java
  src/main/java/com/acon/server/member/application/mapper/RecentViewedSpotMapper.java
  src/main/java/com/acon/server/member/application/mapper/ViewedSpotMapper.java
  src/main/java/com/acon/server/member/application/service/MemberService.java
  src/main/java/com/acon/server/member/domain/entity/GuidedSpot.java
  src/main/java/com/acon/server/member/domain/entity/Member.java
  src/main/java/com/acon/server/member/domain/entity/ViewedSpot.java
  src/main/java/com/acon/server/member/infra/entity/GuidedSpotEntity.java
  src/main/java/com/acon/server/member/infra/entity/VerifiedAreaEntity.java
  src/main/java/com/acon/server/member/infra/entity/ViewedSpotEntity.java
  src/main/java/com/acon/server/member/infra/repository/GuidedSpotRepository.java
  src/main/java/com/acon/server/member/infra/repository/RecentGuidedSpotRepository.java
  src/main/java/com/acon/server/review/domain/entity/Review.java
  src/main/java/com/acon/server/spot/api/controller/SpotController.java
  src/main/java/com/acon/server/spot/api/response/MenuListResponse.java
  src/main/java/com/acon/server/spot/api/response/SpotDetailResponse.java
  src/main/java/com/acon/server/spot/application/mapper/SpotDtoMapper.java
  src/main/java/com/acon/server/spot/application/service/SpotService.java
  src/main/java/com/acon/server/spot/domain/entity/OpeningHour.java
  src/main/java/com/acon/server/spot/domain/entity/Spot.java
  src/main/java/com/acon/server/spot/domain/enums/Day.java
  src/main/java/com/acon/server/spot/infra/entity/MenuEntity.java
  src/main/java/com/acon/server/spot/infra/entity/OpeningHourEntity.java
  src/main/java/com/acon/server/spot/infra/entity/SpotEntity.java
  src/main/java/com/acon/server/spot/infra/entity/SpotImageEntity.java
  src/main/java/com/acon/server/spot/infra/entity/SpotOptionEntity.java
  src/main/java/com/acon/server/spot/infra/repository/MenuRepository.java
  src/main/java/com/acon/server/spot/infra/repository/OpeningHourRepository.java
  src/main/java/com/acon/server/spot/infra/repository/SpotImageRepository.java
  src/main/java/com/acon/server/spot/infra/repository/SpotRepository.java
Labels: ✨ FEAT, 🐈‍⬛ 창균, size/L

#13 [ FEAT/#11] 구글 로그인 API 구현
  .gitignore
  build.gradle
  src/main/java/com/acon/server/ServerApplication.java
  src/main/java/com/acon/server/common/auth/jwt/JwtUtils.java
  src/main/java/com/acon/server/common/auth/jwt/config/JwtConfig.java
  src/main/java/com/acon/server/global/exception/ErrorType.java
  src/main/java/com/acon/server/member/api/controller/MemberController.java
  src/main/java/com/acon/server/member/api/request/LoginRequest.java
  src/main/java/com/acon/server/member/api/request/PreferenceRequest.java
  src/main/java/com/acon/server/member/api/response/.gitkeep
  src/main/java/com/acon/server/member/api/response/AcornCountResponse.java
  src/main/java/com/acon/server/member/api/response/LoginResponse.java
  src/main/java/com/acon/server/member/application/service/MemberService.java
  src/main/java/com/acon/server/member/domain/entity/Preference.java
  src/main/java/com/acon/server/member/domain/enums/FavoriteSpot.java
  src/main/java/com/acon/server/member/domain/enums/SpotStyle.java
  src/main/java/com/acon/server/member/infra/external/.gitkeep
  src/main/java/com/acon/server/member/infra/external/google/GoogleSocialService.java
  src/main/java/com/acon/server/member/infra/external/google/config/GoogleConfig.java
  src/main/java/com/acon/server/member/infra/repository/MemberRepository.java
  src/main/java/com/acon/server/member/infra/repository/PreferenceRepository.java
  src/main/java/com/acon/server/spot/application/service/SpotService.java
Labels: ✨ FEAT, 🦊 가현, size/L

#27 [FEAT/#26] 장소 검색 API 구현
  src/main/java/com/acon/server/spot/api/controller/SpotController.java
  src/main/java/com/acon/server/spot/api/response/SearchSpotListResponse.java
  src/main/java/com/acon/server/spot/api/response/SearchSpotResponse.java
  src/main/java/com/acon/server/spot/application/service/SpotService.java
  src/main/java/com/acon/server/spot/infra/repository/SpotRepository.java
Labels: ✨ FEAT, 🦊 가현, size/S

#34 [FEAT/#30] 동네 인증 API 구현
  build.gradle
  src/main/java/com/acon/server/ServerApplication.java
  src/main/java/com/acon/server/global/external/NaverMapsClient.java
  src/main/java/com/acon/server/member/api/controller/MemberController.java
  src/main/java/com/acon/server/member/api/request/MemberAreaRequest.java
  src/main/java/com/acon/server/member/api/response/MemberAreaResponse.java
  src/main/java/com/acon/server/member/application/service/MemberService.java
  src/main/java/com/acon/server/member/infra/repository/VerifiedAreaRepository.java
Labels: ✨ FEAT, 🦊 가현, size/S

#38 [FEAT/#35] 위치 인증 API 구현
  build.gradle
  src/main/java/com/acon/server/member/application/service/MemberService.java
  src/main/java/com/acon/server/spot/api/controller/SpotController.java
  src/main/java/com/acon/server/spot/api/response/VerifiedSpotResponse.java
  src/main/java/com/acon/server/spot/application/service/SpotService.java
  src/main/java/com/acon/server/spot/infra/repository/SpotRepository.java
Labels: ✨ FEAT, 🦊 가현, size/S

#42 [FIX/#41] 전체 동작 확인
  build.gradle
  src/main/java/com/acon/server/common/auth/jwt/JwtUtils.java
  src/main/java/com/acon/server/common/auth/jwt/config/JwtConfig.java
  src/main/java/com/acon/server/global/exception/ErrorType.java
  src/main/java/com/acon/server/global/external/NaverMapsClient.java
  src/main/java/com/acon/server/member/api/controller/MemberController.java
  src/main/java/com/acon/server/member/api/request/LoginRequest.java
  src/main/java/com/acon/server/member/api/request/MemberAreaRequest.java
  src/main/java/com/acon/server/member/application/service/MemberService.java
  src/main/java/com/acon/server/member/infra/entity/MemberEntity.java
  src/main/java/com/acon/server/member/infra/external/google/GoogleSocialService.java
  src/main/java/com/acon/server/member/infra/external/google/config/GoogleConfig.java
  src/main/java/com/acon/server/spot/api/controller/SpotController.java
  src/main/java/com/acon/server/spot/api/response/.gitkeep
  src/main/java/com/acon/server/spot/application/service/.gitkeep
  src/main/java/com/acon/server/spot/application/service/SpotService.java
  src/main/java/com/acon/server/spot/domain/entity/SpotOption.java
  src/main/java/com/acon/server/spot/infra/repository/SpotRepository.java
Labels: 🛠️ FIX, 🐈‍⬛ 창균, size/M

#40 [FIX/#39] 최근 길 안내 장소 조회 오류 해결
  src/main/java/com/acon/server/member/application/service/MemberService.java
  src/main/java/com/acon/server/member/domain/entity/GuidedSpot.java
  src/main/java/com/acon/server/member/infra/repository/GuidedSpotRepository.java
Labels: 🛠️ FIX, 🦊 가현, size/S

#43 [FEAT/#37] 추천 검색어 조회 API 구현
  src/main/java/com/acon/server/member/api/controller/MemberController.java
  src/main/java/com/acon/server/member/application/service/MemberService.java
  src/main/java/com/acon/server/member/infra/repository/GuidedSpotRepository.java
  src/main/java/com/acon/server/spot/api/controller/SpotController.java
  src/main/java/com/acon/server/spot/api/response/SearchSuggestionListResponse.java
  src/main/java/com/acon/server/spot/api/response/SearchSuggestionResponse.java
  src/main/java/com/acon/server/spot/application/mapper/SpotDtoMapper.java
  src/main/java/com/acon/server/spot/application/service/SpotService.java
  src/main/java/com/acon/server/spot/domain/entity/Spot.java
  src/main/java/com/acon/server/spot/infra/entity/SpotEntity.java
  src/main/java/com/acon/server/spot/infra/repository/SpotRepository.java
Labels: ✨ FEAT, 🐈‍⬛ 창균, size/M

#45 [FEAT/#44] 리뷰 작성 API 구현
  src/main/java/com/acon/server/global/exception/ErrorType.java
  src/main/java/com/acon/server/global/external/NaverMapsAdapter.java
  src/main/java/com/acon/server/global/external/NaverMapsClient.java
  src/main/java/com/acon/server/global/scheduler/SpotScheduler.java
  src/main/java/com/acon/server/member/api/controller/MemberController.java
  src/main/java/com/acon/server/member/application/service/MemberService.java
  src/main/java/com/acon/server/member/domain/entity/Member.java
  src/main/java/com/acon/server/member/domain/entity/Preference.java
  src/main/java/com/acon/server/member/infra/repository/VerifiedAreaRepository.java
  src/main/java/com/acon/server/review/api/controller/.gitkeep
  src/main/java/com/acon/server/review/api/controller/ReviewController.java
  src/main/java/com/acon/server/review/api/request/ReviewRequest.java
  src/main/java/com/acon/server/review/application/service/ReviewService.java
  src/main/java/com/acon/server/review/infra/repository/.gitkeep
  src/main/java/com/acon/server/review/infra/repository/ReviewRepository.java
  src/main/java/com/acon/server/spot/api/controller/SpotController.java
  src/main/java/com/acon/server/spot/application/service/SpotService.java
  src/main/java/com/acon/server/spot/domain/entity/Spot.java
  src/main/java/com/acon/server/spot/infra/repository/SpotRepository.java
Labels: ✨ FEAT, 🐈‍⬛ 창균, size/L

#50 [FIX/#48] 행정동에서 법정동 변경
  src/main/java/com/acon/server/global/external/NaverMapsAdapter.java
  src/main/java/com/acon/server/member/application/service/MemberService.java
  src/main/java/com/acon/server/review/application/service/ReviewService.java
  src/main/java/com/acon/server/spot/application/service/SpotService.java
  src/main/java/com/acon/server/spot/domain/entity/Spot.java
  src/main/java/com/acon/server/spot/infra/entity/SpotEntity.java
  src/main/java/com/acon/server/spot/infra/repository/SpotRepository.java
Labels: 🛠️ FIX, 🦊 가현, size/S

#53 [FEAT/#49] 스프링 시큐리티를 통한 임시 인증 인가 처리 로직 추가
  build.gradle
  src/main/java/com/acon/server/global/auth/MemberAuthentication.java
  src/main/java/com/acon/server/global/auth/PrincipalHandler.java
  src/main/java/com/acon/server/global/auth/filter/CustomAccessDeniedHandler.java
  src/main/java/com/acon/server/global/auth/filter/CustomJwtAuthenticationEntryPoint.java
  src/main/java/com/acon/server/global/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/acon/server/global/auth/jwt/JwtTokenProvider.java
  src/main/java/com/acon/server/global/auth/jwt/JwtValidationType.java
  src/main/java/com/acon/server/global/auth/security/SecurityConfig.java
  src/main/java/com/acon/server/member/api/controller/MemberController.java
  src/main/java/com/acon/server/member/api/request/LoginRequest.java
  src/main/java/com/acon/server/member/application/service/MemberService.java
  src/main/java/com/acon/server/review/application/service/ReviewService.java
  src/main/java/com/acon/server/spot/application/service/SpotService.java
Labels: ✨ FEAT, 🐈‍⬛ 창균, size/L

#55 [FEAT/#54] 애플 로그인 구현
  src/main/java/com/acon/server/global/auth/jwt/JwtTokenProvider.java
  src/main/java/com/acon/server/global/config/OpenFeignConfig.java
  src/main/java/com/acon/server/member/application/service/MemberService.java
  src/main/java/com/acon/server/member/infra/external/google/GoogleSocialService.java
  src/main/java/com/acon/server/member/infra/external/ios/AppleAuthAdapter.java
  src/main/java/com/acon/server/member/infra/external/ios/AppleAuthClient.java
  src/main/java/com/acon/server/member/infra/external/ios/ApplePublicKey.java
  src/main/java/com/acon/server/member/infra/external/ios/ApplePublicKeyGenerator.java
  src/main/java/com/acon/server/member/infra/external/ios/ApplePublicKeyResponse.java
Labels: ✨ FEAT, 🐈‍⬛ 창균, size/M

#56 [FEAT/#52] 메인 페이지 상세 조건 필터링 구현
  src/main/java/com/acon/server/spot/api/request/SpotListRequest.java
  src/main/java/com/acon/server/spot/application/service/SpotService.java
  src/main/java/com/acon/server/spot/domain/enums/CafeFeature.java
  src/main/java/com/acon/server/spot/domain/enums/CompanionType.java
  src/main/java/com/acon/server/spot/domain/enums/FilterCategory.java
  src/main/java/com/acon/server/spot/domain/enums/RestaurantFeature.java
  src/main/java/com/acon/server/spot/domain/enums/VisitPurpose.java
  src/main/java/com/acon/server/spot/infra/repository/SpotNativeQueryRepository.java
Labels: ✨ FEAT, 🦊 가현, size/L

#60 [FIX/#59] 동네 인증 에러 수정
  src/main/java/com/acon/server/member/application/service/MemberService.java
  src/main/java/com/acon/server/member/domain/entity/GuidedSpot.java
  src/main/java/com/acon/server/member/domain/entity/VerifiedArea.java
  src/main/java/com/acon/server/member/infra/repository/VerifiedAreaRepository.java
Labels: 🛠️ FIX, 🦊 가현, size/S

#62 [FIX/#61] 검색어 오류 수정
  src/main/java/com/acon/server/spot/application/service/SpotService.java
  src/main/java/com/acon/server/spot/infra/repository/SpotRepository.java
Labels: 🛠️ FIX, 🦊 가현, size/S

#67 [REFACTOR/#66] 추천 검색어 조회 API 로직 수정
  src/main/java/com/acon/server/member/infra/repository/GuidedSpotCustomRepository.java
  src/main/java/com/acon/server/spot/application/service/SpotService.java
Labels: ✨ FEAT, 🐈‍⬛ 창균, size/M

#65 [FEAT/#64] 위치 기반 법정동 조회 API 구현
  src/main/java/com/acon/server/member/api/controller/MemberController.java
  src/main/java/com/acon/server/member/application/service/MemberService.java
  src/main/java/com/acon/server/member/infra/repository/GuidedSpotCustomRepository.java
  src/main/java/com/acon/server/spot/application/service/SpotService.java
Labels: ✨ FEAT, 🐈‍⬛ 창균, size/M

#63 [FEAT/#57] 위치 기반 장소 추천 알고리즘 구현
  src/main/java/com/acon/server/global/auth/PrincipalHandler.java
  src/main/java/com/acon/server/global/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/acon/server/member/api/controller/MemberController.java
  src/main/java/com/acon/server/member/application/service/MemberService.java
  src/main/java/com/acon/server/member/domain/enums/Cuisine.java
  src/main/java/com/acon/server/member/domain/enums/FavoriteSpot.java
  src/main/java/com/acon/server/member/domain/enums/SpotStyle.java
  src/main/java/com/acon/server/member/infra/repository/GuidedSpotCustomRepository.java
  src/main/java/com/acon/server/member/infra/repository/PreferenceRepository.java
  src/main/java/com/acon/server/spot/api/controller/SpotController.java
  src/main/java/com/acon/server/spot/api/request/.gitkeep
  src/main/java/com/acon/server/spot/api/request/SpotListRequest.java
  src/main/java/com/acon/server/spot/api/response/SpotListResponse.java
  src/main/java/com/acon/server/spot/application/service/SpotService.java
  src/main/java/com/acon/server/spot/domain/entity/Spot.java
  src/main/java/com/acon/server/spot/domain/vo/.gitkeep
  src/main/java/com/acon/server/spot/domain/vo/SpotWithScore.java
  src/main/java/com/acon/server/spot/infra/repository/OptionRepository.java
  src/main/java/com/acon/server/spot/infra/repository/SpotNativeQueryRepository.java
  src/main/java/com/acon/server/spot/infra/repository/SpotOptionRepository.java
  src/main/java/com/acon/server/spot/infra/repository/SpotRepository.java
Labels: ✨ FEAT, 🐈‍⬛ 창균, size/L
